email:          zj7687362@gmail.com

keep_files:     ['.git','.svn']

encoding:       "utf-8"
permalink:      /:year/:month/:day/:title

blogname:       "JackZhang's Blog"
staticurl:      "http://jcore.qiniudn.com"

baseurl:        ""

paginate:       6
paginate_path:  "page:num"

markdown:       kramdown
