email:          zj7687362@gmail.com

keep_files:     ['.git','.svn']

encoding:       "utf-8"
permalink:      /:year/:month/:day/:title

blogname:       "JackZhang's Blog"
staticurl:      "http://7q5apr.com1.z0.glb.clouddn.com"

baseurl:        ""
url:            "http://www.jcore.cn"

paginate:       10
paginate_path:  "page:num"

markdown:       kramdown 
