email:          zj7687362@gmail.com

keep_files:     ['.git','.svn']

encoding:       "utf-8"
permalink:      /:year/:month/:day/:title

blogname:       "JackZhang's Blog"
staticurl:      ""

baseurl:        ""

paginate:       5
paginate_path:  "page:num"

markdown:       kramdown
