email: zj7687362@gmail.com

keep_files:   	['.git','.svn']

encoding:     	"utf-8"
permalink: 	  	/:year/:month/:day/:title

blogname: 	  	"JackZhang's Blog"
blogurl: 	  	http://localhost:4000

baseurl: 	  	""

paginate: 		5
paginate_path:  "page:num"

markdown: 		kramdown
